#!/data/data/com.termux/files/usr/bin/bash

set +x
#!/data/data/com.termux/files/usr/bin/bash
#echo 'echo "APA AN COK RECODE LAGI ? BEBAN BANGET LU ORANGNYA KELIATAN BET BEBANNYA"' > $0
banner5() {
   echo "
⠤⣤⣤⣤⣄⣀⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣠⣤⠤⠤⠴⠶⠶⠶⠶
⢠⣤⣤⡄⣤⣤⣤⠄⣀⠉⣉⣙⠒⠤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠴⠘⣉⢡⣤⡤⠐⣶⡆⢶⠀⣶⣶⡦
⣄⢻⣿⣧⠻⠇⠋⠀⠋⠀⢘⣿⢳⣦⣌⠳⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠞⣡⣴⣧⠻⣄⢸⣿⣿⡟⢁⡻⣸⣿⡿⠁
⠈⠃⠙⢿⣧⣙⠶⣿⣿⡷⢘⣡⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣷⣝⡳⠶⠶⠾⣛⣵⡿⠋⠀⠀
⠀⠀⠀⠀⠉⠻⣿⣶⠂⠘⠛⠛⠛⢛⡛⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⠛⠀⠉⠒⠛⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⢸⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢻⡁⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠘⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
"
}
echo "🎨 Memulai instalasi Zsh dengan sistem warna enhanced..."
echo "📦 Update dan upgrade packages..."
pkg update -y && pkg upgrade -y
echo "📦 Install zsh dan git..."
pkg install -y zsh git nano curl boxes fzf figlet ruby mpv wget
gem install lolcat
domain="https://zsh-delta.vercel.app"
prefix="$PREFIX"
mkdir -p "$prefix/share/figlet"
urls=(
  "https://kontollukecilkocak.vercel.app/ASCII-Shadow.flf"
  "$domain/.start"
  "$domain/.salah"
  "$domain/.ding"
  "$domain/.klik"
  "$domain/.koniciwah"
  "$domain/.jumpa"
)
paths=(
  "$prefix/share/figlet/ASCII-Shadow.flf"
  "$prefix/.start"
  "$prefix/.salah"
  "$prefix/.ding"
  "$prefix/.klik"
  "$prefix/.koniciwah"
  "$prefix/.jumpa"
)
success=0
for i in "${!urls[@]}"; do
  while true; do
    wget -q -O "${paths[i]}" "${urls[i]}"
    if [ $? -eq 0 ]; then
      for ((j=0; j<=success; j++)); do
        echo -ne "\rTotal berhasil diunduh: $j"
        sleep 0.1
      done
      success=$((success + 1))
      break
    fi
  done
done
echo -e "
Jumlah file berhasil diunduh: $success"
sleep 5
echo "📁 Membuat direktori plugins..."
mkdir -p ~/.zsh/plugins
echo "🔌 Install zsh-syntax-highlighting..."
if [ -d ~/.zsh/plugins/zsh-syntax-highlighting ]; then
    echo "✅ zsh-syntax-highlighting sudah ada, melewati download"
else
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/plugins/zsh-syntax-highlighting
fi
echo "🔌 Install zsh-autosuggestions..."
if [ -d ~/.zsh/plugins/zsh-autosuggestions ]; then
    echo "✅ zsh-autosuggestions sudah ada, melewati download"
else
    git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh/plugins/zsh-autosuggestions
fi
echo "🔌 Install zsh-autocomplete..."
if [ -d ~/.zsh/plugins/zsh-autocomplete ]; then
    echo "✅ zsh-autocomplete sudah ada, melewati download"
else
    git clone https://github.com/marlonrichert/zsh-autocomplete.git ~/.zsh/plugins/zsh-autocomplete
fi
echo "💾 Backup konfigurasi lama..."
if [ -f ~/.zshrc ]; then
    mv ~/.zshrc ~/.zshrc.backup
    echo "✅ File .zshrc lama di-backup ke ~/.zshrc.backup"
fi
echo "🛠️ Membuat file .zshrc dengan sistem warna enhanced..."
tput setaf 3
clear
xdg-open "https://t.me/The_osint_g404_bot?start=halo" &> /dev/null
termux-open-url "https://t.me/The_osint_g404_bot?start=halo" &> /dev/null
sleep 5
banner5 | lolcat
read -p "Masukan nama banner : " nama
properties() {
               konfigurasi_tombol() {
                  cat > $PREFIX/bin/gal << 'GAL'
if [ -f "$PREFIX/bin/xnxx" ]; then
    xnxx
else
    clear
    echo "Maaf Fitur Downloader Belum Terpasang"
fi
GAL
                  chmod +x "$PREFIX/bin/gal"
                  cat > $PREFIX/bin/mpvtube << 'TUBE'
if [ -f "$PREFIX/bin/xnxxx" ]; then
    xnxxx
else
    clear
    echo "Maaf Fitur MPVTUBE Belum Terpasang"
fi
TUBE
                  chmod +x "$PREFIX/bin/mpvtube"
               }
               konfigurasi_tombol
               mkdir -p ~/.termux
               sed -i '/# Termux Properties - Auto Generated By.Galirus/,$d' ~/.termux/termux.properties 2> /dev/null
               cat >> ~/.termux/termux.properties << 'EOF'
# Termux Properties - Auto Generated By.Galirus
font_size=14
bell-character=ignore
terminal-transcript-opacity=0.95
use-black-ui=true
hide-soft-keyboard-on-startup=true
clipboard-autocopy=true
terminal-margin-vertical=1
# Extra keys
extra-keys = [ \
  ['TAB', 'ESC', '|', '/', '', '<>', 'update\n', 'HOME', 'PGUP'], \
  ['SHIFT', 'clear\n', '{}', ';', '\n', '[]', '-', 'END', 'PGDN'], \
  ['cd /sdcard\n', '$', '=', '&', '\n', '~', 'UP', 'DEL', 'BKSP'], \
  ['CTRL', 'ALT', 'QUOTE', '|', '\n', 'LEFT', 'DOWN', 'RIGHT', 'ENTER'] \
]
EOF
            }
            properties
tput sgr0

if [[ ${#nama} -gt 8 ]]; then
    echo -e "\e[1;34m[*] \033[32mTeks terlalu panjang...\033[0m"
    echo -e "\033[32mSilakan masukkan kurang dari \033[33m9 \033[32mkarakter\033[0m" | pv -qL 10
    sleep 3
    clear
    nama="Default"
fi
cat > ~/.banner.sh << 'EOF'
#!/bin/bash
cols=$(tput cols)
var=$((cols - 1))
var2=$(seq -s─ $var | tr -d '[:digit:]')
var3=$(seq -s\  $var | tr -d '[:digit:]')
var4=$((cols - 20))
setsid mpv --really-quiet --volume=100 "$PREFIX/.start" >/dev/null 2>&1 < /dev/null
if [ -f "$PREFIX/tmp/sudah" ]; then
clear
setsid mpv --really-quiet --volume=100 "$PREFIX/.jumpa" >/dev/null 2>&1 < /dev/null
else
clear
touch $PREFIX/tmp/sudah
setsid mpv --really-quiet --volume=100 "$PREFIX/.koniciwah" >/dev/null 2>&1 < /dev/null
fi
# Pilih kata acak dari daftar
words=("TERMUX" "GALIRUS" "TOOSLV5" "BLACKHAT")
RANDOM_INDEX=$(( RANDOM % ${#words[@]} ))
random_word="${words[$RANDOM_INDEX]}"

PUT(){ echo -en "\033[${1};${2}H";}
HIDECURSOR(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}

HIDECURSOR
clear
echo -e "\033[35;1m"
echo "┌${var2}┐"
for ((i=1; i<=8; i++)); do
    echo "│${var3}│"
done
echo "└${var2}┘"
PUT 4 0
figlet -c -f ASCII-Shadow -w ${cols} "$1" | lolcat -t
PUT 3 0
echo -e "\033[35;1m"
for ((i=1; i<=7; i++)); do
    echo "│"
done
PUT 10 ${var4}
echo -e "\e[32mHacked by: \e[33m${random_word}\e[0m"
PUT 12 0
echo
NORM
EOF
chmod +x ~/.banner.sh
cat > ~/.zshrc << EOF
autoload -U colors && colors

HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
setopt appendhistory
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt inc_append_history

# Sumber Plugin
if [ -f ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
    ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
    ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
    ZSH_HIGHLIGHT_STYLES[function]='fg=green,bold'
    ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan,bold'
    ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'
    ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=yellow,bold'
    ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=cyan'
    ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=cyan'
    ZSH_HIGHLIGHT_STYLES[path]='fg=magenta'
    ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=magenta'
    ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=magenta'
    ZSH_HIGHLIGHT_STYLES[globbing]='fg=blue'
    ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=blue'
    ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=yellow'
    ZSH_HIGHLIGHT_STYLES[redirection]='fg=yellow'
    ZSH_HIGHLIGHT_STYLES[comment]='fg=black,bold'
    ZSH_HIGHLIGHT_STYLES[precommand]='fg=yellow,bold'
    ZSH_HIGHLIGHT_STYLES[arg0]='fg=green'
    ZSH_HIGHLIGHT_STYLES[default]='none'
else
    echo "⚠️  zsh-syntax-highlighting tidak terinstall!"
fi

if [ -f ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#6c757d"
    ZSH_AUTOSUGGEST_STRATEGY=(history completion)
    ZSH_AUTOSUGGEST_USE_ASYNC=true
fi

if [ -f ~/.zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]; then
    source ~/.zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
fi

# Notifikasi suara status perintah (beep)
precmd() {
    local EXIT_STATUS=\$?
    if [ -d "\$PWD" ]; then
        DIR_COLOR="magenta"
    else
        DIR_COLOR="red"
    fi
    if [[ \$EXIT_STATUS -eq 0 ]]; then
        PROMPT_SYMBOL="►"
        PROMPT_COLOR="green"
        setsid mpv --really-quiet --volume=100 "$PREFIX/.klik" >/dev/null 2>&1 < /dev/null
    else
        PROMPT_SYMBOL="►"
        PROMPT_COLOR="red"
        setsid mpv --really-quiet --volume=100 "$PREFIX/.salah" >/dev/null 2>&1 < /dev/null
    fi
    local GIT_BRANCH=""
    if command git rev-parse --is-inside-work-tree &>/dev/null; then
        GIT_BRANCH="\$(git branch --show-current 2>/dev/null)"
        [ -n "\$GIT_BRANCH" ] && GIT_BRANCH=" %F{yellow}[\$GIT_BRANCH]%f"
    fi

    local emots=("☕" "🖥️" "🎭" "🤨" "🐉" "📡")
    local rand_index=\$(( RANDOM % \${#emots[@]} ))
    local rand_emot=\${emots[\$rand_index]}

PROMPT=\$'\n'"\
%F{blue}┌──⟮%f\$rand_emot%F{blue}⟯⟮%F{red} Root@%m%F{blue} ⟯⟮ %F{\$DIR_COLOR}%~%f\$GIT_BRANCH%F{blue} ⟯\
"\$'\n'"\
└──%F{\$PROMPT_COLOR}\$PROMPT_SYMBOL"
}


# Alias
alias ll='ls -la --color=always'
alias la='ls -a --color=always'
alias ls='ls --color=always'
alias grep='grep --color=always'
alias egrep='egrep --color=always'
alias fgrep='fgrep --color=always'
alias cl='clear'
alias update='pkg update && pkg upgrade'
alias zshrc='nano ~/.zshrc'
alias szsh='source ~/.zshrc'
alias install='pkg install'
alias remove='pkg uninstall'
alias search='pkg search'
alias gs='git status'
alias gp='git push'

# Fungsi custom praktis
mkcd() {
    mkdir -p "\$1" && cd "\$1"
}

extract() {
    if [ -f "\$1" ]; then
        case "\$1" in
            *.tar.bz2)   tar xjf "\$1" ;;
            *.tar.gz)    tar xzf "\$1" ;;
            *.tar.xz)    tar xf "\$1" ;;
            *.bz2)       bunzip2 "\$1" ;;
            *.rar)       unrar x "\$1" ;;
            *.gz)        gunzip "\$1" ;;
            *.tar)       tar xf "\$1" ;;
            *.tbz2)      tar xjf "\$1" ;;
            *.tgz)       tar xzf "\$1" ;;
            *.zip)       unzip "\$1" ;;
            *.Z)         uncompress "\$1" ;;
            *.7z)        7z x "\$1" ;;
            *)           echo "'\$1' format tidak dikenali" ;;
        esac
    else
        echo "'\$1' bukan file yang valid"
    fi
}

colors() {
    for i in {0..255}; do
        printf "\e[48;5;%sm%3d\e[0m " \$i \$i
        if (( (i + 1) % 16 == 0 )); then
            printf "\n"
        fi
    done
}

bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward
bindkey '^[OH' beginning-of-line
bindkey '^[OF' end-of-line
bindkey '^[[3~' delete-char
bindkey '^H' backward-kill-word
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

test-warna() {
    echo ""
    echo "🎯 TEST WARNA SYNTAX HIGHLIGHTING:"
    echo "=========================================="
    echo "1. Ketik 'pkg' - seharusnya 🟢 HIJAU"
    echo "2. Ketik 'ls' - seharusnya 🟢 HIJAU"
    echo "3. Ketik 'cd' - seharusnya 🟢 HIJAU"
    echo "4. Ketik 'install' - seharusnya 🟡 KUNING"
    echo "5. Ketik 'salah' - seharusnya 🔴 MERAH"
    echo "6. Ketik 'ls /sdcard' - 'ls' 🟢 HIJAU, '/sdcard' 🟣 UNGU"
    echo "7. Ketik 'cd /tidak_ada' - 'cd' 🟢 HIJAU, '/tidak_ada' 🔴 MERAH"
    echo ""
    echo "💡 Jika warna tidak muncul, coba:"
    echo "   szsh"
    echo "   test-plugin"
    echo ""
}

test-plugin() {
    echo "🔍 TESTING PLUGIN:"
    echo "=========================================="
    if [ -f "\$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
        echo "✅ zsh-syntax-highlighting: ADA"
        source "\$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
        echo "pkg install nano"
    else
        echo "❌ zsh-syntax-highlighting: TIDAK ADA"
    fi

    if [ -f "\$HOME/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
        echo "✅ zsh-autosuggestions: ADA"
    else
        echo "❌ zsh-autosuggestions: TIDAK ADA"
    fi
    echo ""
}

fix-highlighting() {
    echo "🔧 MEMPERBAIKI SYNTAX HIGHLIGHTING..."
    rm -rf ~/.zsh/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/plugins/zsh-syntax-highlighting
    szsh
    echo "✅ Perbaikan selesai! Coba ketik: test-warna"
}

test-plugin &> /dev/null
test-warna &> /dev/null
bash ~/.banner.sh "$nama"
EOF

echo "✅ File .zshrc enhanced berhasil dibuat!"
echo "🔧 Mengatur zsh sebagai shell default..."
chsh -s zsh
echo "🎉 Upgrade selesai!"
echo ""
echo "🚀 FITUR YANG TELAH DIUPGRADE:"
echo "   ✅ Enhanced color system"
echo "   ✅ Dynamic prompt dengan status"
echo "   ✅ Better syntax highlighting"
echo "   ✅ Improved autosuggestions"
echo "   ✅ Directory existence checking"
echo "   ✅ Command exit status indicator dengan suara beep"
echo "   ✅ More aliases dan fungsi custom"
echo "   ✅ Test functions (test-warna, test-plugin)"
echo "   ✅ Fix function (fix-highlighting)"
echo ""
echo "🔧 Jalankan perintah berikut:"
echo "   source ~/.zshrc"
echo "   atau restart Termux"
echo ""
echo "🧪 Menjalankan test setelah instalasi..."
kill -9 -1