 #!/data/data/com.termux/files/usr/bin/bash
#echo 'echo "APA AN COK RECODE LAGI ? BEBAN BANGET LU ORANGNYA KELIATAN BET BEBANNYA"' > $0
tampilan_utama(){
banner5() {
   echo '
⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣠⣤⣤⣼⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀
⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀
⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀
⠀⠀⠀⠘⣿⣿⣿⣿⠟⠁⠀⠀⠀⠹⣿⣿⣿⣿⣿⠟⠁⠀⠀⠹⣿⣿⡿⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣿⣿⣿⡇⠀⠀⠀⢼⣿⠀⢿⣿⣿⣿⣿⠀⣾⣷⠀⠀⢿⣿⣷⠀⠀⠀⠀⠀
⠀⠀⠀⢠⣿⣿⣿⣷⡀⠀⠀⠈⠋⢀⣿⣿⣿⣿⣿⡀⠙⠋⠀⢀⣾⣿⣿⠀⠀⠀⠀⠀
⢀⣀⣀⣀⣿⣿⣿⣿⣿⣶⣶⣶⣶⣿⣿⣿⣿⣾⣿⣷⣦⣤⣴⣿⣿⣿⣿⣤⠤⢤⣤⡄
⠈⠉⠉⢉⣙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⣀⣀⣀⡀⠀
⠐⠚⠋⠉⢀⣬⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣥⣀⡀⠈⠀⠈⠛
⠀⠀⠴⠚⠉⠀⠀⠀⠉⠛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠋⠁⠀⠀⠀⠉⠛⠢⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀
'
}
echo "🎨 Memulai instalasi Zsh dengan sistem warna enhanced..."
echo "📦 Update dan upgrade packages..."
pkg update -y && pkg upgrade -y
echo "📦 Install zsh dan git..."
pkg install -y zsh git nano curl boxes fzf figlet ruby mpv wget pipes.sh tgpt
gem install lolcat
domain="https://zsh-delta.vercel.app"
prefix="$PREFIX"
mkdir -p "$prefix/share/figlet"
urls=(
  "https://kontollukecilkocak.vercel.app/ASCII-Shadow.flf"
  "$domain/.start"
  "$domain/.salah"
  "$domain/.ding"
  "$domain/.klik"
  "$domain/.koniciwah"
  "$domain/.jumpa"
)
paths=(
  "$prefix/share/figlet/ASCII-Shadow.flf"
  "$prefix/.start"
  "$prefix/.salah"
  "$prefix/.ding"
  "$prefix/.klik"
  "$prefix/.koniciwah"
  "$prefix/.jumpa"
)
success=0
for i in "${!urls[@]}"; do
  while true; do
    wget -q -O "${paths[i]}" "${urls[i]}"
    if [ $? -eq 0 ]; then
      for ((j=0; j<=success; j++)); do
        echo -ne "\rTotal berhasil diunduh: $j"
        sleep 0.1
      done
      success=$((success + 1))
      break
    fi
  done
done
echo -e "
Jumlah file berhasil diunduh: $success"
sleep 5
echo "📁 Membuat direktori plugins..."
mkdir -p ~/.zsh/plugins
echo "🔌 Install zsh-syntax-highlighting..."
if [ -d ~/.zsh/plugins/zsh-syntax-highlighting ]; then
    echo "✅ zsh-syntax-highlighting sudah ada, melewati download"
else
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/plugins/zsh-syntax-highlighting
fi
echo "🔌 Install zsh-autosuggestions..."
if [ -d ~/.zsh/plugins/zsh-autosuggestions ]; then
    echo "✅ zsh-autosuggestions sudah ada, melewati download"
else
    git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh/plugins/zsh-autosuggestions
fi
echo "🔌 Install zsh-autocomplete..."
if [ -d ~/.zsh/plugins/zsh-autocomplete ]; then
    echo "✅ zsh-autocomplete sudah ada, melewati download"
else
    git clone https://github.com/marlonrichert/zsh-autocomplete.git ~/.zsh/plugins/zsh-autocomplete
fi
echo "💾 Backup konfigurasi lama..."
if [ -f ~/.zshrc ]; then
    mv ~/.zshrc ~/.zshrc.backup
    echo "✅ File .zshrc lama di-backup ke ~/.zshrc.backup"
fi
echo "🛠️ Membuat file .zshrc dengan sistem warna enhanced..."
tput setaf 3
clear
xdg-open "https://www.youtube.com/@GalirusProjects" &> /dev/null | dialog --msgbox "SUBSCRIBE DULU CHANNEL SAYA" 6 50
termux-open-url "https://www.youtube.com/@GalirusProjects" &> /dev/null  | dialog --msgbox "KU BILANG SUBSCRIBE DULU CHANNEL SAYA !!!" 6 50
clear
banner5 | lolcat
read -p "Masukan nama banner : " nama
echo "$nama" > ~/.banner_name
properties() {
               konfigurasi_tombol() {
                  cat > $PREFIX/bin/gal << 'GAL'
if [ -f "$PREFIX/bin/xnxx" ]; then
    xnxx
else
    clear
    echo "Maaf Fitur Downloader Belum Terpasang"
fi
GAL
                  chmod +x "$PREFIX/bin/gal"
                  cat > $PREFIX/bin/mpvtube << 'TUBE'
if [ -f "$PREFIX/bin/xnxxx" ]; then
    xnxxx
else
    clear
    echo "Maaf Fitur MPVTUBE Belum Terpasang"
fi
TUBE
                  chmod +x "$PREFIX/bin/mpvtube"
               }
               konfigurasi_tombol
               mkdir -p ~/.termux
               sed -i '/# Termux Properties - Auto Generated By.Galirus/,$d' ~/.termux/termux.properties 2> /dev/null
               cat >> ~/.termux/termux.properties << 'EOF'
# Termux Properties - Auto Generated By.Galirus
font_size=10
bell-character=ignore
terminal-transcript-opacity=0.95
use-black-ui=true
hide-soft-keyboard-on-startup=true
clipboard-autocopy=true
terminal-margin-vertical=1
# Extra keys
extra-keys = [ \
  ['TAB', 'ESC', '|', '/', '', 'keluar\n', 'update\n', 'HOME', 'PGUP'], \
  ['SHIFT', 'clear\n', '{}', ';', '\n', '[]', '-', 'END', 'PGDN'], \
  ['cd /sdcard\n', '$', '=', '&', '\n', '~', 'UP', 'DEL', 'BKSP'], \
  ['CTRL', 'ALT', 'QUOTE', '|', '\n', 'LEFT', 'DOWN', 'RIGHT', 'ENTER'] \
]
EOF
            }
            properties
tput sgr0

if [[ ${#nama} -gt 8 ]]; then
    echo -e "\e[1;34m[*] \033[32mTeks terlalu panjang...\033[0m"
    echo -e "\033[32mSilakan masukkan kurang dari \033[33m9 \033[32mkarakter\033[0m" | pv -qL 10
    sleep 3
    clear
    nama="Default"
fi


cat > $PREFIX/bin/pipes.sh << 'EOF'
#!/data/data/com.termux/files/usr/bin/env bash
f=100
p=2
turbo=15

M=32768 s=13 r=2000 t=0
sets=("┃┏ ┓┛━┓  ┗┃┛┗ ┏━" "│╭ ╮╯─╮  ╰│╯╰ ╭─" "│┌ ┐┘─┐  └│┘└ ┌─" "║╔ ╗╝═╗  ╚║╝╚ ╔═" "|+ ++-+  +|++ +-" "|/ \/-\  \|/\ /-" ".. ....  .... .." ".o oo.o  o.oo o." "-\ /\|/  /-\/ \|" "╿┍ ┑┚╼┒  ┕╽┙┖ ┎╾")
SETS=(); x=(); y=(); l=(); n=(); v=(); c=(); V=(); C=(); VN=0; CN=0; E=()
RNDSTART=1 BOLD=1 NOCOLOR=0 KEEPCT=0

START_TIME=$(date +%s)

cleanup() {
    tput reset; tput rmcup; tput cnorm; stty echo
    exit 0
}

resize() { w=$(tput cols); h=$(tput lines); }

init_pipes() {
    local i; ci=$((KEEPCT ? 0 : CN * RANDOM / M)); vi=$((KEEPCT ? 0 : VN * RANDOM / M))
    for ((i = 0; i < p; i++)); do
        ((n[i]=0, l[i]=RANDOM%4, x[i]=w*RANDOM/M, y[i]=h*RANDOM/M, v[i]=V[vi]))
        c[i]=${E[ci]}; ((ci=(ci+1)%CN, vi=(vi+1)%VN))
    done
}

main() {
    tput -T "$TERM" sgr0 >/dev/null || return $?
    COLORS=$(tput colors); SGR0=$(tput sgr0); SGR_BOLD=$(tput bold)
    V=(0); VN=1; C=(1 2 3 4 5 6 7 0); CN=8
    for ((i=0; i<CN; i++)); do
        E[i]=$SGR0; ((BOLD)) && E[i]+=$SGR_BOLD; ((NOCOLOR)) || E[i]+=$(tput setaf ${C[i]})
    done
    for ((i=0; i<${#sets[@]}; i++)); do
        for ((j=0; j<16; j++)); do SETS+=("${sets[i]:j:1}"); done
    done
    
    stty -echo; tput smcup; tput civis; tput clear
    trap cleanup HUP TERM; resize; trap resize SIGWINCH
    init_pipes

    while true; do
        (( $(date +%s) - START_TIME >= 5 )) && break
        
        read -t 0.01 -n 1 2>/dev/null
        [[ -n "$REPLY" ]] && break
        
        for ((step=0; step < turbo; step++)); do
            for ((i=0; i<p; i++)); do
           
                ((l[i] % 2)) && ((x[i] += -l[i] + 2, 1)) || ((y[i] += l[i] - 1))
                ((!KEEPCT && (x[i] >= w || x[i] < 0 || y[i] >= h || y[i] < 0))) && { c[i]=${E[CN * RANDOM / M]}; ((v[i] = V[VN * RANDOM / M])); }
                ((x[i] = (x[i] + w) % w, y[i] = (y[i] + h) % h))
                ((n[i] = s * RANDOM / M - 1, n[i] = n[i] >= 0 ? l[i] : l[i] + (2 * (RANDOM % 2) - 1), n[i] = (n[i] + 4) % 4))
                printf '\e[%d;%dH%s%s' $((y[i] + 1)) $((x[i] + 1)) ${c[i]} "${SETS[v[i] * 16 + l[i] * 4 + n[i]]}"
                l[i]=${n[i]}
            done
        done 
        ((r > 0 && t * p >= r)) && tput reset && tput civis && t=0 || ((t++))
    done
    cleanup
}
main "$@"
EOF
chmod +x $PREFIX/bin/pipes.sh
cat > $PREFIX/lib/bash/.banner.sh << 'EOF'
#!/bin/bash
cols=$(tput cols)
var=$((cols - 1))
var2=$(seq -s─ $var | tr -d '[:digit:]')
var3=$(seq -s\  $var | tr -d '[:digit:]')
var4=$((cols - 20))
if [ -f "$PREFIX/tmp/sudah" ]; then
clear
setsid mpv --really-quiet --volume=100 "$PREFIX/.jumpa" >/dev/null 2>&1 < /dev/null
else
setsid mpv --really-quiet --volume=100 "$PREFIX/.start" >/dev/null 2>&1 < /dev/null &
pipes.sh
clear
touch $PREFIX/tmp/sudah
fi

words=("TERMUX" "GALIRUS" "TOOSLV5" "BLACKHAT")
RANDOM_INDEX=$(( RANDOM % ${#words[@]} ))
random_word="${words[$RANDOM_INDEX]}"

PUT(){ echo -en "\033[${1};${2}H";}
HIDECURSOR(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}

HIDECURSOR
clear
echo -e "\033[38;5;129;1m"
echo "┌${var2}┐"
for ((i=1; i<=8; i++)); do
    echo "│${var3}│"
done
echo "└${var2}┘"
PUT 4 0
figlet -c -f ASCII-Shadow -w ${cols} "$1" | lolcat -t
PUT 3 0
echo -e "\033[38;5;129;1m"
for ((i=1; i<=7; i++)); do
    echo "│"
done
PUT 10 ${var4}
echo -e "\e[32mHacked by: \e[33m${random_word}\e[0m"
PUT 12 0
echo
NORM
EOF
chmod +x $PREFIX/lib/bash/.banner.sh
cat > ~/.zshrc << 'EOF'
autoload -U colors && colors
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

zstyle ':completion:*' delay 0
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':autocomplete:tab-insert' fzf

HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
setopt appendhistory
setopt INTERACTIVE_COMMENTS
setopt NO_HIST_EXPAND
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt inc_append_history
setopt PROMPT_SUBST

if [ -f ~/.zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]; then
    source ~/.zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
fi

if [ -f ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#6c757d"
    ZSH_AUTOSUGGEST_USE_ASYNC=true
fi

if [ -f ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

    ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
    ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
    ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan,bold'    
    ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold,underline'    
    ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=yellow,bold'   
    ZSH_HIGHLIGHT_STYLES[path]='fg=129,bold'
    
    ZSH_HIGHLIGHT_PATTERNS+=('*.sh' 'fg=blue,bold')
    ZSH_HIGHLIGHT_PATTERNS+=('*.py' 'fg=blue,bold')
    ZSH_HIGHLIGHT_PATTERNS+=('*.js' 'fg=blue,bold')
    ZSH_HIGHLIGHT_PATTERNS+=('*.cpp' 'fg=blue,bold')
    ZSH_HIGHLIGHT_PATTERNS+=('*.php' 'fg=blue,bold')
    
    ZSH_HIGHLIGHT_PATTERNS+=('*.txt' 'fg=yellow,bold')
    ZSH_HIGHLIGHT_PATTERNS+=('*.md' 'fg=yellow,bold')
    ZSH_HIGHLIGHT_PATTERNS+=('*.log' 'fg=yellow,bold')
    
    ZSH_HIGHLIGHT_STYLES[globbing]='fg=white'
fi

precmd() {
    integer EXIT_STATUS=$?

    if [[ -d "$PWD" ]]; then
        DIR_COLOR="magenta"
    else
        DIR_COLOR="red"
    fi

    local emots rand_index rand_emot
    if (( EXIT_STATUS == 0 )); then
        PROMPT_SYMBOL="►"
        PROMPT_COLOR="green"
        emots=("😁👍" "😎👍" "😉👍" "😇👍")
        setsid mpv --really-quiet --volume=100 "$PREFIX/.klik" >/dev/null 2>&1 < /dev/null
    else
        PROMPT_SYMBOL="►"
        PROMPT_COLOR="red"
        emots=("😒👎" "🤨👎" "😠👎" "🙁👎")
        setsid mpv --really-quiet --volume=100 "$PREFIX/.salah" >/dev/null 2>&1 < /dev/null

        if command -v tgpt &>/dev/null; then
            local last_cmd=$(fc -ln -1 | sed 's/^[[:space:]]*//')
            local tmp_ai="$PREFIX/tmp/ai_res.txt"
            timeout 10s tgpt "Jangan gunakan markdown. Jelaskan singkat kenapa perintah '$last_cmd' gagal (exit code $EXIT_STATUS) di Termux dan solusinya." 2>/dev/null | grep -v "Loading" | sed "s/\`//g" > "$tmp_ai"
            if [ -s "$tmp_ai" ]; then
                dialog --backtitle "🤖 AI ERROR ASSISTANT" --title " ANALISIS ERROR: $last_cmd " --msgbox "$(cat "$tmp_ai")" 0 0
            fi
            rm -f "$tmp_ai"
        fi
    fi

    rand_index=$(( RANDOM % ${#emots[@]} + 1 ))
    rand_emot=${emots[$rand_index]}

    local GIT_BRANCH=""
    if command git rev-parse --is-inside-work-tree &>/dev/null; then
        GIT_BRANCH="$(git branch --show-current 2>/dev/null)"
        [[ -n "$GIT_BRANCH" ]] && GIT_BRANCH=" %F{yellow}[$GIT_BRANCH]%f"
    fi
    RPROMPT=""

    PROMPT=$'\n'"\
%F{blue}┌──⟮%f$rand_emot%F{blue}⟯─⟮%F{red} $(cat ~/.banner_name)@%m%F{blue} ⟯─⟮ %F{$DIR_COLOR}%~%f$GIT_BRANCH%F{blue} ⟯\
"$'\n'"\
└──%F{$PROMPT_COLOR}$PROMPT_SYMBOL "
}
alias ll='ls -la --color=always'
alias la='ls -a --color=always'
alias ls='ls --color=always'
alias grep='grep --color=always'
alias cl='clear'

alias update='pkg update && pkg upgrade'
alias install='pkg install'
alias hapus-paket='pkg uninstall'
alias cari='pkg search'
alias keluar='kill -9 -1'
alias zshrc='nano ~/.zshrc'
alias szsh='source ~/.zshrc'
alias clone='git clone --depth 32'
alias gs='git status'
alias gp='git push'

alias bantuan='Bantuan'

bs() {
    if [[ $# -eq 0 ]]; then
        echo "❌ Penggunaan: bs <script.sh>"
        return 1
    fi
    bash "$@"
}

folder() {
    if [[ -z "$1" ]]; then
        echo "❌ Penggunaan: folder <nama_folder>"
        return 1
    fi
    mkdir -p "$1" && cd "$1"
}

hapus() {
    if [[ $# -eq 0 ]]; then
        echo "❌ Penggunaan: hapus <file/folder>"
        return 1
    fi
    rm -rf "$@" && echo "✅ Berhasil dihapus"
}

extract() {
    if [[ ! -f "$1" ]]; then
        echo "❌ '$1' bukan file valid"
        return 1
    fi

    case "$1" in
        *.tar.bz2) tar xjf "$1" ;;
        *.tar.gz)  tar xzf "$1" ;;
        *.tar.xz)  tar xf  "$1" ;;
        *.zip)     unzip  "$1" ;;
        *.7z)      7z x   "$1" ;;
        *) echo "❌ Format tidak dikenali" ;;
    esac
}


Bantuan() {
  case "$1" in
    ""|--help|-h)
      echo -e "
📌 PUSAT BANTUAN TERMINAL

🔹 FILE & NAVIGASI
  ll              → ls -la (detail + tersembunyi)
  la              → ls -a
  ls              → ls berwarna
  cl              → bersihkan layar
  grep            → cari teks

🔹 MANAJEMEN PAKET
  update          → update & upgrade paket
  install <pkg>   → install paket
  hapus-paket <pkg> → uninstall paket
  cari <nama>     → cari paket

🔹 ZSH
  zshrc           → edit ~/.zshrc
  szsh            → reload zsh

🔹 GIT
  clone           → git clone 
  gs              → git status
  gp              → git pull

🔹 FUNCTION TAMBAHAN
  bs <file.sh>    → jalankan script bash
  folder <nama>   → buat & masuk folder
  hapus <target>  → hapus file/folder
  extract <file>  → ekstrak arsip

🔹 BANTUAN
  bantuan         → tampilkan menu ini
  bantuan alias   → tampilkan semua alias
"
    ;;
    alias)
      echo "📌 DAFTAR ALIAS AKTIF:"
      alias
    ;;
    *)
      echo "❌ Opsi tidak dikenal: $1"
      echo "Gunakan: bantuan --help"
    ;;
  esac
}

export LS_COLORS="di=1;129:fi=0;34:*.txt=1;33:*.md=1;33:*.log=1;33:ex=1;32"
echo -ne '\e[2 q'

bindkey '^[[A' up-line-or-history
bindkey '^[[B' down-line-or-history
bindkey '^[[3~' delete-char
bash $PREFIX/lib/bash/.banner.sh "$(cat ~/.banner_name 2>/dev/null)"
EOF

chsh -s zsh
echo "✅ File .zshrc berhasil dibuat!"
sleep 3
clear
dialog --msgbox "Silahkan Keluar Dari Script Ini Untuk melihat hasil"  6 50
}

export DIALOGRC="$HOME/.dialogrc"
create_dialog_config() {
    cat > "$HOME/.dialogrc" << 'EOF'
use_shadow = ON
use_colors = ON
screen_color = (CYAN,BLACK,ON)
dialog_color = (WHITE,BLACK,ON)
title_color = (YELLOW,BLACK,ON)
border_color = (WHITE,BLACK,ON)
button_active_color = (BLACK,CYAN,ON)
button_inactive_color = (WHITE,BLACK,ON)
button_key_active_color = (BLACK,CYAN,ON)
button_key_inactive_color = (WHITE,BLACK,ON)
button_label_active_color = (BLACK,CYAN,ON)
button_label_inactive_color = (WHITE,BLACK,ON)
inputbox_color = (WHITE,BLACK,ON)
inputbox_border_color = (WHITE,BLACK,ON)
searchbox_color = (WHITE,BLACK,ON)
searchbox_title_color = (YELLOW,BLACK,ON)
searchbox_border_color = (WHITE,BLACK,ON)
position_indicator_color = (YELLOW,BLACK,ON)
menubox_color = (WHITE,BLACK,ON)
menubox_border_color = (WHITE,BLACK,ON)
item_color = (WHITE,BLACK,ON)
item_selected_color = (BLACK,CYAN,ON)
tag_color = (YELLOW,BLACK,ON)
tag_selected_color = (BLACK,CYAN,ON)
tag_key_color = (CYAN,BLACK,ON)
tag_key_selected_color = (BLACK,CYAN,ON)
check_color = (WHITE,BLACK,ON)
check_selected_color = (BLACK,CYAN,ON)
uarrow_color = (GREEN,BLACK,ON)
darrow_color = (GREEN,BLACK,ON)
EOF
}

check_dialog() {
    if ! command -v dialog >/dev/null 2>&1; then
        echo "📦 Menginstall dialog..."
        pkg install -y dialog
        if [ $? -ne 0 ]; then
            echo "❌ Gagal install dialog!"
            exit 1
        fi
    fi
    
    create_dialog_config
}

BACKUP_FLAG_FILE="$HOME/.termux_backup_flag"
LATEST_BACKUP_DIR=""
CURRENT_SHELL=$(basename "$SHELL")
INSTALL_LOG="$HOME/.termux_install.log"

log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$INSTALL_LOG"
}

check_existing_backup() {
    if [ -f "$BACKUP_FLAG_FILE" ]; then
        LATEST_BACKUP_DIR=$(cat "$BACKUP_FLAG_FILE" 2>/dev/null)
        if [ -d "$LATEST_BACKUP_DIR" ]; then
            return 0
        else
            rm -f "$BACKUP_FLAG_FILE"
        fi
    fi
    
    local latest_backup=$(ls -d $HOME/.termux_backup_* 2>/dev/null | sort -r | head -1)
    if [ -n "$latest_backup" ] && [ -d "$latest_backup" ]; then
        LATEST_BACKUP_DIR="$latest_backup"
        echo "$latest_backup" > "$BACKUP_FLAG_FILE"
        return 0
    fi
    
    return 1
}


backup_shell_configs() {
    local backup_dir="$HOME/.termux_backup_$(date +%Y%m%d_%H%M%S)"
    
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "🔐 MEMBUAT BACKUP" \
           --infobox "Membackup konfigurasi shell..." 5 50
    
    mkdir -p "$backup_dir"
    
    local files_to_backup=(
        "$PREFIX/etc/bash.bashrc"
        "$PREFIX/etc/zshrc"
        "$HOME/.bashrc"
        "$HOME/.zshrc"
    )
    
    local backup_names=(
        "bash.bashrc"
        "zshrc_system"
        "bashrc_user"
        "zshrc_user"
    )
    
    local backed_up=0
    local total_files=${#files_to_backup[@]}
    
    for i in "${!files_to_backup[@]}"; do
        if [ -f "${files_to_backup[$i]}" ]; then
            cp "${files_to_backup[$i]}" "$backup_dir/${backup_names[$i]}"
            backed_up=$((backed_up + 1))
        fi
    done
    
    cat > "$backup_dir/restore.sh" << 'EOF'
#!/data/data/com.termux/files/usr/bin/bash
dialog --backtitle "TERMUX BACKUP RESTORE" --title "RESTORING" --infobox "Memulai proses restore..." 5 50
sleep 2

# Restore files
[ -f "bash.bashrc" ] && cp "bash.bashrc" "$PREFIX/etc/bash.bashrc"
[ -f "zshrc_system" ] && cp "zshrc_system" "$PREFIX/etc/zshrc"
[ -f "bashrc_user" ] && cp "bashrc_user" "$HOME/.bashrc"
[ -f "zshrc_user" ] && cp "zshrc_user" "$HOME/.zshrc"

dialog --backtitle "TERMUX BACKUP RESTORE" --title "SUKSES" --msgbox "Restore berhasil!\nRestart Termux untuk efek perubahan." 7 50
EOF
    
    chmod +x "$backup_dir/restore.sh"
    cat > "$backup_dir/INFO.txt" << EOF
BACKUP TIME: $(date)
SHELL: $CURRENT_SHELL
FILES BACKED UP: $backed_up/$total_files
LOCATION: $backup_dir
EOF
    
    LATEST_BACKUP_DIR="$backup_dir"
    echo "$backup_dir" > "$BACKUP_FLAG_FILE"
    
    log_message "Backup created: $backup_dir ($backed_up files)"
    
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "✅ BACKUP SELESAI" \
           --msgbox "Backup berhasil dibuat!\n\nLokasi: $(basename $backup_dir)\nFile: $backed_up/$total_files" 8 50
    
    return 0
}

auto_backup_configs() {
    if check_existing_backup; then
        local backup_age=$(stat -c %Y "$LATEST_BACKUP_DIR" 2>/dev/null)
        local current_age=$(date +%s)
        local diff_hours=$(( (current_age - backup_age) / 3600 ))
        
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "🔍 DETEKSI BACKUP" \
               --yesno "Backup ditemukan:\n\n$(basename $LATEST_BACKUP_DIR)\n($diff_hours jam yang lalu)\n\nGunakan backup ini?" 10 50
        
        if [ $? -eq 0 ]; then
            return 0
        fi
    fi
    
    backup_shell_configs
    return $?
}

show_main_menu() {
    while true; do
        # Get backup status
        local backup_status="❌ TIDAK ADA"
        if check_existing_backup; then
            local backup_name=$(basename "$LATEST_BACKUP_DIR")
            local backup_time=$(stat -c %y "$LATEST_BACKUP_DIR" 2>/dev/null | cut -d' ' -f1)
            backup_status="✅ $backup_name ($backup_time)"
        fi
        
        # Main menu dengan dialog
        choice=$(dialog --backtitle "🎨 TERMUX THEME INSTALLER © GALIRUS 2025" \
                        --title " MENU UTAMA " \
                        --no-cancel \
                        --menu "\nStatus Backup: $backup_status\nShell Aktif: $CURRENT_SHELL" 15 50 5 \
                        1 "📥 PASANG TEMA BARU" \
                        2 "↩️  RESTORE BACKUP" \
                        3 "📋 KELOLA BACKUP" \
                        4 "🔧 SETTINGS" \
                        0 "🚪 KELUAR" \
                        3>&1 1>&2 2>&3)
        
        case $choice in
            1) install_theme_menu ;;
            2) restore_backup_menu ;;
            3) manage_backup_menu ;;
            4) settings_menu ;;
            0) exit_menu ;;
        esac
    done
}

install_theme_menu() {
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "📥 PASANG TEMA" \
           --yesno "Proses ini akan:\n\n1. Backup konfigurasi saat ini\n2. Install tema baru\n3. Ubah tampilan Termux\n\nLanjutkan?" 12 50
    
    if [ $? -ne 0 ]; then
        return
    fi
    
    # Step 1: Auto backup
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "🔐 BACKUP KONFIGURASI" \
           --infobox "Memeriksa dan membuat backup..." 5 50
    sleep 2
    
    if ! auto_backup_configs; then
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "❌ GAGAL" \
               --msgbox "Backup gagal!\nInstalasi dibatalkan." 6 50
        return
    fi
    
   
    theme_choice=$(dialog --backtitle "TERMUX THEME INSTALLER" \
                          --title "🎨 PILIH TEMA" \
                          --menu "Pilih tema yang ingin diinstall:" 15 50 4 \
                          1 "🌟 GALIRUS PREMIUM" \
                          2 "🎭 HACKER STYLE" \
                          3 "🌈 COLORFUL" \
                          4 "⚡ MINIMALIST" \
                          3>&1 1>&2 2>&3)
    
    if [ $? -ne 0 ]; then
        return
    fi
    
   
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "⚠️  KONFIRMASI" \
           --yesno "Anda akan menginstall:\n\n$(get_theme_name $theme_choice)\n\nBackup: $(basename $LATEST_BACKUP_DIR)\n\nLanjutkan instalasi?" 12 50
    
    if [ $? -ne 0 ]; then
        return
    fi
    
   
    clear  # Clear dialog dulu
    echo "🚀 Starting installation..."
    echo ""
    
    
    case $theme_choice in
        1) 
            echo "🎨 Installing: GALIRUS PREMIUM"
            echo "═══════════════════════════════════════"
            tampilan_utama
            ;;
        2)
            echo "🎭 Installing: HACKER STYLE"
            echo "═══════════════════════════════════════"
            execute_hacker_style
            ;;
        3)
            echo "🌈 Installing: COLORFUL"
            echo "═══════════════════════════════════════"
            execute_colorful
            ;;
        4)
            echo "⚡ Installing: MINIMALIST"
            echo "═══════════════════════════════════════"
            execute_minimalist
            ;;
    esac
    
 
    echo ""
    echo "═══════════════════════════════════════"
    echo "✅ INSTALATION COMPLETE!"
    echo "🎨 Theme: $(get_theme_name $theme_choice)"
    echo "📁 Backup: $(basename $LATEST_BACKUP_DIR)"
    echo ""
    echo "💡 Restart Termux or run: source ~/.zshrc"
    echo ""
    read -p "Press Enter to continue..."
    
 
    show_main_menu
}


get_theme_name() {
    case $1 in
        1) echo "GALIRUS PREMIUM" ;;
        2) echo "HACKER STYLE" ;;
        3) echo "COLORFUL" ;;
        4) echo "MINIMALIST" ;;
        *) echo "UNKNOWN" ;;
    esac
}

execute_hacker_style() {
dialog --msgbox " Masih Dalam Pengembangan Yah !"  6 50
}

execute_colorful() {
dialog   --msgbox " Masih Dalam Pengembangan Yah !" 6 50
}

execute_minimalist() {
dialog   --msgbox " Masih Dalam Pengembangan Yah !"  6 50
}
restore_backup_menu() {
    if ! check_existing_backup; then
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "❌ TIDAK ADA BACKUP" \
               --msgbox "Tidak ada backup yang ditemukan!" 6 50
        return
    fi
    
 
    restore_choice=$(dialog --backtitle "TERMUX THEME INSTALLER" \
                            --title "↩️  RESTORE BACKUP" \
                            --menu "Backup terbaru:\n$(basename $LATEST_BACKUP_DIR)" 12 50 3 \
                            1 "Restore backup terbaru" \
                            2 "Pilih dari daftar" \
                            3 "Compare dengan saat ini" \
                            3>&1 1>&2 2>&3)
    
    case $restore_choice in
        1) restore_latest_backup ;;
        2) select_backup_to_restore ;;
        3) compare_with_current ;;
    esac
}

restore_latest_backup() {
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "🔄 RESTORE" \
           --yesno "Restore dari:\n\n$(basename $LATEST_BACKUP_DIR)\n\nKonfigurasi saat ini akan diganti!" 10 50
    
    if [ $? -ne 0 ]; then
        return
    fi
    
 
    {
        echo "50"
        echo "# Restoring files..."
        if [ -f "$LATEST_BACKUP_DIR/restore.sh" ]; then
            bash "$LATEST_BACKUP_DIR/restore.sh" > /dev/null 2>&1
        else
            # Manual restore
            [ -f "$LATEST_BACKUP_DIR/bash.bashrc" ] && cp "$LATEST_BACKUP_DIR/bash.bashrc" "$PREFIX/etc/bash.bashrc"
            [ -f "$LATEST_BACKUP_DIR/zshrc_system" ] && cp "$LATEST_BACKUP_DIR/zshrc_system" "$PREFIX/etc/zshrc"
            [ -f "$LATEST_BACKUP_DIR/bashrc_user" ] && cp "$LATEST_BACKUP_DIR/bashrc_user" "$HOME/.bashrc"
            [ -f "$LATEST_BACKUP_DIR/zshrc_user" ] && cp "$LATEST_BACKUP_DIR/zshrc_user" "$HOME/.zshrc"
        fi
        echo "100"
        echo "# Restore selesai!"
    } | dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "PROGRESS" \
               --gauge "Memulihkan konfigurasi..." 8 50
    
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "✅ SUKSES" \
           --msgbox "Restore berhasil!\nRestart Termux." 6 50
    
    log_message "Restored from: $(basename $LATEST_BACKUP_DIR)"
}

select_backup_to_restore() {
    local backups=($(ls -d "$HOME"/.termux_backup_* 2>/dev/null | sort -r))

    if [ ${#backups[@]} -eq 0 ]; then
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "❌ TIDAK ADA" \
               --msgbox "Tidak ada backup!" 6 50
        return
    fi

    local backup_list=()
    for i in "${!backups[@]}"; do
        local name=$(basename "${backups[$i]}")
        local date=$(stat -c %y "${backups[$i]}" 2>/dev/null | cut -d' ' -f1)
        backup_list+=("$((i+1))" "$name ($date)")
    done

    local selected=$(dialog --backtitle "TERMUX THEME INSTALLER" \
                            --title "📋 PILIH BACKUP" \
                            --menu "Pilih backup untuk restore:" 15 50 5 \
                            "${backup_list[@]}" \
                            3>&1 1>&2 2>&3)

    [ -z "$selected" ] && return

    local backup_index=$((selected - 1))
    local selected_backup="${backups[$backup_index]}"

    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "🔄 RESTORE" \
           --yesno "Restore dari:\n\n$(basename "$selected_backup")\n\nKonfigurasi saat ini akan diganti!" 10 50 || return

    export NCURSES_NO_UTF8_ACS=1

    (
        echo "5";   echo "# Menyiapkan restore..."
        sleep 0.2

        if [ -f "$selected_backup/bash.bashrc" ]; then
            echo "25"; echo "# Restore bash.bashrc"
            cp "$selected_backup/bash.bashrc" "$PREFIX/etc/bash.bashrc"
            sleep 0.2
        fi

        if [ -f "$selected_backup/zshrc_system" ]; then
            echo "40"; echo "# Restore zshrc system"
            cp "$selected_backup/zshrc_system" "$PREFIX/etc/zshrc"
            sleep 0.2
        fi

        if [ -f "$selected_backup/bashrc_user" ]; then
            echo "60"; echo "# Restore .bashrc user"
            cp "$selected_backup/bashrc_user" "$HOME/.bashrc"
            sleep 0.2
        fi

        if [ -f "$selected_backup/zshrc_user" ]; then
            echo "80"; echo "# Restore .zshrc user"
            cp "$selected_backup/zshrc_user" "$HOME/.zshrc"
            sleep 0.2
        fi

        echo "90"; echo "# Set default shell ke bash"
        chsh -s bash
        sleep 0.2

        echo "100"; echo "# Restore selesai!"
    ) | dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "PROGRESS" \
               --gauge "Memulihkan backup..." 8 50

    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "✅ SUKSES" \
           --msgbox "Restore berhasil!" 6 50

    log_message "Restored from: $(basename "$selected_backup")"
}

manage_backup_menu() {
    local backups=($(ls -d $HOME/.termux_backup_* 2>/dev/null | sort -r))
    
    if [ ${#backups[@]} -eq 0 ]; then
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "📭 KOSONG" \
               --msgbox "Tidak ada backup!" 6 50
        return
    fi
    
    local backup_items=()
    for i in "${!backups[@]}"; do
        local name=$(basename "${backups[$i]}")
        local date=$(stat -c %y "${backups[$i]}" 2>/dev/null | cut -d' ' -f1)
        local file_count=$(ls -1 "${backups[$i]}" | wc -l)
        backup_items+=("$((i+1))" "$name" "$date" "$file_count files")
    done
    
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "📋 DAFTAR BACKUP" \
           --extra-button --extra-label "OPSI" \
           --ok-label "INFO" \
           --cancel-label "KEMBALI" \
           --menu "" 15 60 5 \
           "${backup_items[@]}" \
           2> $PREFIX/tmp//backup_selection
    
    local button=$?
    local selection=$(cat $PREFIX/tmp//backup_selection 2>/dev/null)
    
    if [ $button -eq 0 ]; then  # INFO button
        if [ -n "$selection" ]; then
            local index=$((selection - 1))
            show_backup_info "${backups[$index]}"
        fi
    elif [ $button -eq 3 ]; then  # OPSI button
        show_backup_options "$selection"
    fi
}

show_backup_info() {
    local backup_dir="$1"
    local info_file="$backup_dir/INFO.txt"
    
    if [ -f "$info_file" ]; then
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "📄 INFO BACKUP" \
               --textbox "$info_file" 12 60
    else
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "📄 INFO BACKUP" \
               --msgbox "Nama: $(basename $backup_dir)\nLokasi: $backup_dir\nFile: $(ls -1 "$backup_dir" | wc -l) items" 8 50
    fi
}

show_backup_options() {
    local selection=$1
    local backups=($(ls -d $HOME/.termux_backup_* 2>/dev/null | sort -r))
    local index=$((selection - 1))
    local backup_dir="${backups[$index]}"
    
    local option=$(dialog --backtitle "TERMUX THEME INSTALLER" \
                          --title "⚙️  OPSI BACKUP" \
                          --menu "Pilih aksi untuk:\n$(basename $backup_dir)" 12 50 4 \
                          1 "🔍 Lihat Detail" \
                          2 "🔄 Restore" \
                          3 "🗑️  Hapus" \
                          4 "📤 Export" \
                          3>&1 1>&2 2>&3)
    
    case $option in
        1)
            show_backup_detail "$backup_dir"
            ;;
        2)
            restore_selected_backup "$backup_dir"
            ;;
        3)
            delete_backup "$backup_dir"
            ;;
        4)
            export_backup "$backup_dir"
            ;;
    esac
}

delete_backup() {
    local backup_dir="$1"
    
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "🗑️  HAPUS BACKUP" \
           --yesno "Hapus backup ini?\n\n$(basename $backup_dir)\n\nTindakan ini tidak dapat dibatalkan!" 10 50
    
    if [ $? -eq 0 ]; then
        rm -rf "$backup_dir"
        
        if [ "$backup_dir" = "$LATEST_BACKUP_DIR" ]; then
            rm -f "$BACKUP_FLAG_FILE"
            check_existing_backup
        fi
        
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "✅ TERHAPUS" \
               --msgbox "Backup telah dihapus!" 6 50
        
        log_message "Backup deleted: $(basename $backup_dir)"
    fi
}

settings_menu() {
    while true; do
        local setting_choice=$(dialog --backtitle "TERMUX THEME INSTALLER" \
                                      --title "🔧 SETTINGS" \
                                      --menu "Pengaturan Sistem:" 15 50 5 \
                                      1 "🔐 Buat Backup Manual" \
                                      2 "📊 View Log" \
                                      3 "🔄 Reset Settings" \
                                      4 "ℹ️  System Info" \
                                      0 "⬅ Kembali" \
                                      3>&1 1>&2 2>&3)
        
        case $setting_choice in
            1)
                backup_shell_configs
                ;;
            2)
                view_log_file
                ;;
            3)
                reset_settings
                ;;
            4)
                show_system_info
                ;;
            0)
                break
                ;;
        esac
    done
}

view_log_file() {
    if [ -f "$INSTALL_LOG" ]; then
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "📊 INSTALL LOG" \
               --textbox "$INSTALL_LOG" 20 60
    else
        dialog --backtitle "TERMUX THEME INSTALLER" \
               --title "📊 LOG" \
               --msgbox "Log file tidak ditemukan!" 6 40
    fi
}

show_system_info() {
    local info="=== SYSTEM INFORMATION ===\n"
    info+="OS: $(uname -o)\n"
    info+="Kernel: $(uname -r)\n"
    info+="Arch: $(uname -m)\n"
    info+="Shell: $CURRENT_SHELL\n"
    info+="Termux: $(pkg show termux-api | grep Version | head -1)\n"
    info+="Dialog: $(dialog --version 2>/dev/null | head -1)\n"
    info+="\n=== DISK USAGE ===\n"
    info+="$(df -h $HOME | tail -1)\n"
    info+="\n=== BACKUP STATUS ===\n"
    if check_existing_backup; then
        info+="Latest: $(basename $LATEST_BACKUP_DIR)\n"
        info+="Total: $(ls -d $HOME/.termux_backup_* 2>/dev/null | wc -l) backup(s)\n"
    else
        info+="No backup found\n"
    fi
    
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "ℹ️  SYSTEM INFO" \
           --msgbox "$info" 15 60
}

exit_menu() {
    dialog --backtitle "TERMUX THEME INSTALLER" \
           --title "🚪 KELUAR" \
           --yesno "Yakin ingin keluar?" 6 40
    
    if [ $? -eq 0 ]; then
        clear
        echo "Terima kasih telah menggunakan Termux Theme Installer!"
        echo "© GALIRUS 2025"
        sleep 5
        kill -9 -1
    fi
}

check_dialog
clear
dialog --backtitle "TERMUX THEME INSTALLER" \
       --title " SELAMAT DATANG " \
       --msgbox "🎨 TERMUX THEME INSTALLER\n\n© GALIRUS 2025\n\nTools untuk mengelola tema dan konfigurasi Termux dengan mudah!" 10 50
show_main_menu